<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Tue, 11 Jul 2023 21:56:42 +0000
 */
$conf['title'] = 'APP_SURCENTRO';
$conf['lang'] = 'es';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
