# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 11 Jul 2023 21:56:42 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$FAHEUaQ6tbFgiBD6EjIudegLRFGlRyTNom2tKfP7NaXRjuyAIJBY2:kiron:solartejoseluis@gmail.com:admin,user
